"""The frozen name-the-emotion frames (an#98).

Eight PNGs — one face per preset of the `expressions` corpus scene, cropped to
the head — are the **cassette key** for the emotion judge: ``judge_key`` hashes
their bytes, so they are committed once and never regenerated by a renderer
change. They are deliberately not the goldens (a golden has a re-bless
lifecycle that would silently move the key; see `tests/_vision_cassettes.py`),
only *copied from them*, through ``an``'s own PNG writer, so the bytes are a
function of the decoded pixels and nothing else.

    python tests/_emotion_frames.py        # re-freeze (needs no browser)

Re-running changes the key only if the picture changed; a changed key means the
cassette has to be recorded again, which is the point.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRAMES_DIR = ROOT / "tests" / "fixtures" / "vision_frames" / "emotions"
GOLDEN_DIR = ROOT / "misc" / "bench" / "golden" / "expressions"
#: The label set the judge chooses from, and the corpus shot ids, in shot order.
EMOTION_LABELS: tuple[str, ...] = (
    "neutral", "happy", "sad", "angry", "surprised", "afraid", "thinking", "skeptical",
)
#: (row0, row1, col0, col1): head and brows, nothing below the collar.
FACE_CROP: tuple[int, int, int, int] = (0, 130, 60, 260)


def load_frames(root: Path = FRAMES_DIR) -> dict[str, bytes]:
    """``{label: png bytes}`` for every frozen face present."""
    return {
        label: (root / f"{label}.png").read_bytes()
        for label in EMOTION_LABELS
        if (root / f"{label}.png").is_file()
    }


def freeze(*, golden_dir: Path = GOLDEN_DIR, out: Path = FRAMES_DIR) -> dict[str, Path]:
    """Copy each preset's blessed frame, cropped to the face, into ``out``."""
    from an.bench.png import read_png, write_png

    manifest = json.loads(next(golden_dir.glob("bless-*.json")).read_text(encoding="utf-8"))
    by_shot = {f["shot_id"]: golden_dir / f["file"] for f in manifest["frames"]}
    missing = [label for label in EMOTION_LABELS if label not in by_shot]
    if missing:
        raise RuntimeError(f"the expressions goldens have no frame for {missing}")
    r0, r1, c0, c1 = FACE_CROP
    out.mkdir(parents=True, exist_ok=True)
    written = {}
    for label in EMOTION_LABELS:
        dst = out / f"{label}.png"
        write_png(dst, read_png(by_shot[label])[r0:r1, c0:c1])
        written[label] = dst
    return written


if __name__ == "__main__":
    for label, path in freeze().items():
        print(f"{label}: {path.relative_to(ROOT)}")
